sudo: required
dist: trusty

language: cpp

cache:
  - apt
  - directories:
    - ThirdLibrary/Tools
    - ThirdLibrary/src
    #- ThirdLibrary/unix
    #- ThirdLibrary/windows_mingw

compiler:
  - g++

jdk: oraclejdk7

os:
  - unix

addons:
  ssh_known_hosts:
    - github.com
  
env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBITIM_BUILD_THIRDLIBRARY="TRUE" 

  matrix:
     - BUILD_TARGERT="android" QT_VERSION_DIR=5.7 QT_VERSION=5.7.0 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"
     - BUILD_TARGERT="android" QT_VERSION_DIR=5.6 QT_VERSION=5.6.0 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"
     - BUILD_TARGERT="android" QT_VERSION_DIR=5.5 QT_VERSION=5.5.1 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"


     #- BUILD_TARGERT="unix" RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libpng jpeg libgif libtiff geos gdal libvpx libyuv x264 ffmpeg opencv"
     - BUILD_TARGERT="unix" QT_VERSION_DIR=5.7 QT_VERSION=5.7.0 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"
     - BUILD_TARGERT="unix" QT_VERSION_DIR=5.6 QT_VERSION=5.6.0 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"
     - BUILD_TARGERT="unix" QT_VERSION_DIR=5.5 QT_VERSION=5.5.1 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"
     - BUILD_TARGERT="unix" QT_VERSION_DIR=5.4 QT_VERSION=5.4.2 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"
     - BUILD_TARGERT="unix" QT_VERSION_DIR=5.3 QT_VERSION=5.3.2 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"
     - BUILD_TARGERT="unix" QT_VERSION_DIR=5.2 QT_VERSION=5.2.1 RABBITIM_BUILD_THIRDLIBRARY="zlib minizip openssl libcurl libvpx libyuv x264 ffmpeg qxmpp qzxing rabbitim"

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - bash ThirdLibrary/build_script/ci/build-install-apt.sh > /dev/null
  - bash ThirdLibrary/build_script/ci/build-install-tools.sh > /dev/null

before_script:
  - source ${SOURCE_DIR}/ThirdLibrary/build_script/ci/build_env.sh
  - cd ${SOURCE_DIR}/ThirdLibrary/build_script
  
script: 
  - bash ${SOURCE_DIR}/ThirdLibrary/build_script/ci/build_linux.sh ${SOURCE_DIR}

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

deploy:
  provider: releases
  api_key: 177ce637a8ec54e66ea8693092caf35059cf95d7
  file: 
    - ./build_android/android-build/bin/QtApp-debug.apk
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = android
    repo: KangLin/rabbitim
    tags: true
